### ISSUE TITLE
New lines are not honoured

### ISSUE THREAD

**Issue by gregspeechley** [mflint/ios-tldr-viewer#17] opened 2016-01-06 10:18 UTC
In the description for a command that has multiple lines e.g. curl, a new line just follows on from the existing line rather than starting on the next line.

**Comment by mflint** [comment] 2017-01-28 19:49
Thanks for the bug report Greg. Can't reproduce now, so I wonder if it was fixed in the markdown files. Closing.

**Closed as completed by mflint** 2017-01-28 19:49 UTC
